#!/usr/bin/env bash
#run all args passed

#get user's default shell
#from http://stackoverflow.com/questions/11059067/what-is-the-nix-command-to-view-a-users-default-login-shell
USERSHELL=$(getent passwd $LOGNAME | cut -d: -f7)


CMD=""
for (( i = 1; i <= $#; i++)); do
 eval ARG=\$$i
 CMD="$CMD $(echo "$ARG" | awk '{gsub(".","\\\\&");print}')"
done

echo $CMD

$USERSHELL -c \&\& $CMD

aplay /usr/local/dingle.wav 2>/dev/null
